version: '3.8'
services:
  city-bike-app:
    image: jetty:11-jdk11-alpine
    container_name: city-bike-rest
    ports:
      - "8080:8080"
    volumes:
          - ${PWD}/city-bike-app/target/citybikerest.war:/var/lib/jetty/webapps/root.war