version: '3.8'
services:
  city-bike-app:
    image: jetty:11-jdk11-alpine
    container_name: "city-bike-rest"
    build:
      context: .
      dockerfile: ./city-bike-app/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:5005:5005"
    volumes:
          - ${PWD}/city-bike-app/target/citybikerest.war:/var/lib/jetty/webapps/root.war
          - ${PWD}/config/database.properties:/var/lib/jetty/config/database.properties
  mariadb:
    image: mariadb:10.6.10
    command: --default-authentication-plugin=mysql_native_password
    container_name: "citybike-mariadb"
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_AUTO_UPGRADE: true
      MARIADB_DISABLE_UPGRADE_BACKUP: true
      TZ: "Europe/Helsinki"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ${PWD}/config/my.cnf:/etc/mysql/my.cnf
      - ${PWD}/database/data/csv/2021-05.csv:/journey/2021-05.csv
      - ${PWD}/database/data/csv/2021-06.csv:/journey/2021-06.csv
      - ${PWD}/database/data/csv/2021-07.csv:/journey/2021-07.csv
      - ${PWD}/database/data/csv/station.csv:/station/station.csv
volumes:
  mariadb-data:
